services:
  - type: web
    name: hiremind-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: OPENROUTER_API_KEY
        sync: false  # This should be set manually in Render dashboard
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
    healthCheckPath: /health